# -*- coding: utf-8 -*-
"""Nhận dạng trái cây-finall4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-oivZ4zGZfwcRKmZ80lc0ZpQBVTz5bhM

**TIỀN XỬ LÝ DỮ LIỆU**
"""

# 1. Import thư viện
import os, random, numpy as np, pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from glob import glob
import cv2

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import img_to_array
from tensorflow.keras.applications import MobileNetV2, ResNet50, EfficientNetB0, VGG16
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess
from tensorflow.keras.applications.efficientnet import preprocess_input as efficient_preprocess
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout, Input
from tensorflow.keras.callbacks import EarlyStopping

# Đường dẫn
base_dir = '/content/drive/MyDrive/AI'
train_dir = os.path.join(base_dir, 'train')

# Lấy danh sách file và nhãn
image_paths = []
labels = []
for label in os.listdir(train_dir):
    for fname in os.listdir(os.path.join(train_dir, label)):
        image_paths.append(os.path.join(train_dir, label, fname))
        labels.append(label)

# Tạo DataFrame
df = pd.DataFrame({'filepath': image_paths, 'class': labels})  # dùng 'class' thống nhất

# Chia train/val có stratify
train_df, val_df = train_test_split(df, test_size=0.2, stratify=df['class'], random_state=42)

# Vẽ biểu đồ phân bố class
def plot_class_distribution(df, title):
    counts = df['class'].value_counts()
    counts[:10].plot(kind='bar', title=f"{title} - Top 10")
    plt.show()

plot_class_distribution(train_df, "train")

import cv2
# Kiểm tra shape ảnh và mode màu
shapes = []
for f in train_df['filepath'][:100]:
    img = cv2.imread(f)
    if img is not None:
        shapes.append(img.shape)
    else:
        print(f"Lỗi ảnh (không đọc được): {f}")

modes = []
for f in train_df['filepath'][:100]:
    try:
        img = Image.open(f)
        modes.append(img.mode)
    except:
        modes.append("Error")

from collections import Counter
print(Counter(modes))  # Kiểm tra phân bố màu

#Hiển thị ngẫu nhiên 1 ảnh từ mỗi class (có convert RGB)
class_names = sorted(df['class'].unique())
def show_random_images(data_dir, class_names):
    plt.figure(figsize=(20, 20))
    for i, c in enumerate(class_names[:50]):
        img_extensions = ['*.jpg', '*.jpeg', '*.png']
        imgs = []
        for ext in img_extensions:
            imgs.extend(glob(os.path.join(data_dir, c, ext)))
        if imgs:
            img = Image.open(random.choice(imgs)).convert('RGB')  # convert RGB ở đây
            plt.subplot(10, 5, i+1)
            plt.imshow(img)
            plt.title(c)
            plt.axis('off')
        else:
            print(f"Không tìm thấy ảnh nào cho lớp: {c}")
    plt.tight_layout()
    plt.show()

show_random_images(train_dir, class_names)

image_size = (224, 224)
batch_size = 32

# MobileNetV2
train_gen_mobilenet = ImageDataGenerator(preprocessing_function=mobilenet_preprocess).flow_from_dataframe(
    train_df, x_col='filepath', y_col='class',
    target_size=image_size, class_mode='categorical', batch_size=batch_size)

val_gen_mobilenet = ImageDataGenerator(preprocessing_function=mobilenet_preprocess).flow_from_dataframe(
    val_df, x_col='filepath', y_col='class',
    target_size=image_size, class_mode='categorical', batch_size=batch_size)


# ResNet50
train_gen_resnet = ImageDataGenerator(preprocessing_function=resnet_preprocess).flow_from_dataframe(
    train_df, x_col='filepath', y_col='class',
    target_size=image_size, class_mode='categorical', batch_size=batch_size)

val_gen_resnet = ImageDataGenerator(preprocessing_function=resnet_preprocess).flow_from_dataframe(
    val_df, x_col='filepath', y_col='class',
    target_size=image_size, class_mode='categorical', batch_size=batch_size)


# EfficientNet
train_gen_efficient = ImageDataGenerator(preprocessing_function=efficient_preprocess).flow_from_dataframe(
    train_df, x_col='filepath', y_col='class',
    target_size=image_size, class_mode='categorical', batch_size=batch_size)

val_gen_efficient = ImageDataGenerator(preprocessing_function=efficient_preprocess).flow_from_dataframe(
    val_df, x_col='filepath', y_col='class',
    target_size=image_size, class_mode='categorical', batch_size=batch_size)

"""**XÂY DỰNG HÀM ĐÁNH GIÁ MÔ HÌNH**"""

def evaluate_model(model, val_gen, title):
    import numpy as np
    from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
    import matplotlib.pyplot as plt
    import seaborn as sns

    # Lấy y_true và y_pred theo batch
    y_true = []
    y_pred = []

    for batch_x, batch_y in val_gen:
        preds = model.predict(batch_x)
        y_true.extend(np.argmax(batch_y, axis=1))
        y_pred.extend(np.argmax(preds, axis=1))

        if len(y_true) >= val_gen.samples:
            break

    y_true = np.array(y_true[:val_gen.samples])
    y_pred = np.array(y_pred[:val_gen.samples])

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(10,8))
    sns.heatmap(cm, cmap='Blues', annot=True, fmt='d')
    plt.title(f"Confusion Matrix - {title}")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.show()

    print(f"\nClassification Report - {title}:")
    print(classification_report(y_true, y_pred, digits=4))
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("F1 Score:", f1_score(y_true, y_pred, average='weighted'))

"""**XÂY DỰNG MÔ HÌNH**"""

num_classes = train_df['class'].nunique()

# 1. ResNet50
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping

base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224,224,3))
x = GlobalAveragePooling2D()(base_model.output)
x = Dropout(0.5)(x)
x = Dense(num_classes, activation='softmax')(x)
model_resnet = Model(inputs=base_model.input, outputs=x)

for layer in base_model.layers:
    layer.trainable = False

model_resnet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print("\nTraining ResNet50...")
model_resnet.fit(train_gen_resnet, validation_data=val_gen_resnet, epochs=10, callbacks=[EarlyStopping(patience=3)])
evaluate_model(model_resnet, val_gen_resnet, "ResNet50")

# 2. MobileNetV2
from tensorflow.keras.applications import MobileNetV2

base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224,224,3))
x = GlobalAveragePooling2D()(base_model.output)
x = Dropout(0.5)(x)
x = Dense(num_classes, activation='softmax')(x)
model_mobilenet = Model(inputs=base_model.input, outputs=x)

for layer in base_model.layers:
    layer.trainable = False

model_mobilenet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print("\nTraining MobileNetV2...")
model_mobilenet.fit(train_gen_mobilenet, validation_data=val_gen_mobilenet, epochs=10, callbacks=[EarlyStopping(patience=3)])
evaluate_model(model_mobilenet, val_gen_mobilenet, "MobileNetV2")

# Mô hình EfficientNetV2-B0
from tensorflow.keras.applications import EfficientNetV2B0
from tensorflow.keras.applications.efficientnet_v2 import preprocess_input as efficientv2_preprocess

base_model = EfficientNetV2B0(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
x = GlobalAveragePooling2D()(base_model.output)
x = Dropout(0.5)(x)
output = Dense(num_classes, activation='softmax')(x)
model_efficientv2 = Model(inputs=base_model.input, outputs=output)

# Freeze base model trước (nếu muốn fine-tune thì làm sau vài epoch)
for layer in base_model.layers:
    layer.trainable = False

model_efficientv2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
print("\nTraining EfficientNetV2-B0...")
model_efficientv2.fit(train_gen_efficient, validation_data=val_gen_efficient,
                      epochs=10, callbacks=[EarlyStopping(patience=3)])
evaluate_model(model_efficientv2, val_gen_efficient, "EfficientNetV2-B0")

"""**DỰ ĐOÁN 1 ẢNH**"""

def predict_image(img_path, model_efficientv2, class_indices):
    img = Image.open(img_path).convert('RGB').resize(image_size)
    img_array = efficient_preprocess(img_to_array(img))  # đúng preprocessing
    img_array = np.expand_dims(img_array, axis=0)
    pred = model_efficientv2.predict(img_array)
    class_name = list(class_indices.keys())[np.argmax(pred)]
    print("Prediction:", class_name)
    plt.imshow(img)
    plt.axis('off')
    plt.show()

# Gọi hàm (đảm bảo model đúng tên là model_efficientv2 hoặc sửa tên cho trùng)
predict_image('/content/drive/MyDrive/AI/predict/watermelon (8).png', model_efficientv2, train_gen_efficient.class_indices)

